# Generated by Django 2.2.1 on 2019-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestring', models.CharField(max_length=20)),
                ('shareholding', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
