# Generated by Django 2.2.1 on 2019-05-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccass_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='stockcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
